---
- name: "[📶] cloudflare-ddns"
  community.docker.docker_container:
    name: cloudflare-ddns
    hostname: cloudflare-ddns
    image: favonia/cloudflare-ddns:latest
    pull: true
    user: "1000:1000"
    # Run the updater with user/group ID 1000
    cap_drop:
      - all
      # Drop all other capabilities
    read_only: true
    # Make the container filesystem read-only
    security_opts:
      - no-new-privileges:true
        # Another protection to restrict superuser privileges
    networks:
      - name: internal
    env:
      CF_API_TOKEN: "{{ cloudflare_apikey }}"
      # Your Cloudflare API token
      DOMAINS: "{{ cloudflare_domains | join(',') }}"
      # Your domains (separated by commas)
      PROXIED: "true"
      # Tell Cloudflare to cache webpages and hide your IP
    restart_policy: always
    state: started
